type ContactPoint {
  customer: Customer!
  customerId: ID!
  email: String
  id: ID!
  interactions: [InteractionSummary!]!
  name: String!
  phone: String
  role: String
}

input CreateContactPointInput {
  customerId: ID!
  email: String
  name: String!
  override: Boolean
  phone: String
  role: String
}

input CreateCustomerInput {
  industry: String
  name: String!
  override: Boolean = false
  website: String
}

input CreateEmployeeInput {
  email: String!
  name: String!
}

input CreateInteractionSummaryInput {
  contactPointId: ID!
  date: String!
  message: String!
  type: String!
}

type Customer {
  contactPoints: [ContactPoint!]!
  id: ID!
  industry: String
  interactionCount: Float!
  lastInteraction: InteractionSummary
  name: String!
  website: String
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type Employee {
  email: String!
  id: ID!
  interactions: [InteractionSummary!]!
  name: String!
}

type Hello {
  id: ID!
  message: String!
}

type InteractionSummary {
  contactPoint: ContactPoint!
  contactPointId: ID!
  date: DateTime!
  employee: Employee!
  employeeId: ID!
  id: ID!
  message: String!
  type: String!
}

type Mutation {
  createContactPoint(input: CreateContactPointInput!): ContactPoint!
  createCustomer(input: CreateCustomerInput!): Customer!
  createEmployee(input: CreateEmployeeInput!): Employee!
  createInteractionSummary(input: CreateInteractionSummaryInput!): InteractionSummary!
  deleteContactPoint(id: ID!): ContactPoint!
  deleteCustomer(id: ID!): Customer!
  updateContactPoint(input: UpdateContactPointInput!): ContactPoint!
  updateCustomer(input: UpdateCustomerInput!): Customer!
  updateEmployee(input: UpdateEmployeeInput!): Employee!
}

type Query {
  customer(id: ID!): Customer
  customers: [Customer!]!
  employee(id: ID!): Employee
  employees: [Employee!]!
  getHello(message: String!): Hello!
}

input UpdateContactPointInput {
  customerId: ID
  email: String
  id: ID!
  name: String
  phone: String
  role: String
}

input UpdateCustomerInput {
  id: ID!
  industry: String
  name: String
  website: String
}

input UpdateEmployeeInput {
  email: String
  id: ID!
  name: String
}